### ISSUE TITLE
Where are onemax and xover benchmarks?

### ISSUE THREAD

**Issue by iblancasa** [JJ/goEO#2]
I can't run these two benchmarks and I am new with Go

**Comment by iblancasa** [comment]
Ok, but.. There are a part where maones and xover are benchmarking? A place where I run the code and the program displays:
Go-xover  [numbers numbers numbers]
Go-xover  [numbers numbers numbers]

**Comment by JJ** [comment]
There's probably some error...

2015-11-24 12:48 GMT+01:00 Israel Blancas notifications@github.com:

> Ok, but.. There are a part where maones and xover are benchmarking? A
> place where I run the code and the program displays:
> Go-xover [numbers numbers numbers]
> Go-xover [numbers numbers numbers]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/goEO/issues/2#issuecomment-159242100.

## 

JJ
