### ISSUE TITLE
About griewank

### ISSUE THREAD

**Issue by iblancasa** [JJ/goEO#5]
Why are you adding 1 in this line?

In this implementation https://www.sfu.ca/~ssurjano/Code/griewankm.html thats not happen

```go
func griewank( vec []float64 ) float64 {
	partial_prod := 1.0
	partial_sum := 0.0
	for i,value := range vec {
		good_i := float64(i)+1 // <---here
		partial_prod = partial_prod * math.Cos(value/math.Sqrt(float64(good_i)))
		partial_sum = partial_sum + value*value/4000.0
	}
	return ( partial_sum - partial_prod +1 )
}
```

**Comment by vrivas** [comment]
Because, in order to compute sqrt(i), you have to start in 1, not in 0

**Comment by JJ** [comment]
I is 0, range starts with 1

El miércoles, 2 de noviembre de 2016, Israel Blancas <
notifications@github.com> escribió:

> Why are you adding 1 in this line?
> 
> In this implementation https://www.sfu.ca/~ssurjano/Code/griewankm.html
> thats not happen
> 
> func griewank( vec []float64 ) float64 {
> partial_prod := 1.0
> partial_sum := 0.0
> for i,value := range vec {
> good_i := float64(i)+1 // <---here
> partial_prod = partial_prod \* math.Cos(value/math.Sqrt(float64(good_i)))
> partial_sum = partial_sum + value*value/4000.0
> }
> return ( partial_sum - partial_prod +1 )
> }
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
> https://ci3.googleusercontent.com/proxy/nsF8dKsgIX18lGXGembCoXSsXB2czFEDHYzWk0OWW6gxxmv4B98eW3LCK-GKKOcj7mTTDEyLdKyhrIezddOWI82Xj28G0joXflHXCRdsZgLc6XgmSo7psEcyhDbkjpoOIyqTMQ7aHhwFY-fj6n2RiGfwLEzesA=s0-d-e1-ft#https://github.com/notifications/beacon/AAAB9NOua060WzWPnc9nCXCFqByS0Qohks5q6OpZgaJpZM4KnrRP.gif

## 

JJ

**Comment by iblancasa** [comment]
But.. you should work with `vec[i]`

In the Matlab implementation they work with it.

**Comment by vrivas** [comment]
@iblancasa JJ uses the variable value to store vec[i]

**Comment by JJ** [comment]
True... I'll check that out.

**Comment by JJ** [comment]
That's correct, value = vec[i]

**Comment by iblancasa** [comment]
Oh! Sorry, the syntax of the language.
Thanks
